### ISSUE TITLE
System.OverflowException : Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by IharYakimushEpam** [epam/epam-graphql#98]
### Expected Behavior

Test passed

### Current Behavior

Exception
```
System.OverflowException : Arithmetic operation resulted in an overflow.
   at GraphQL.ValueConverter.<>c.<.cctor>b__1_38(Int64 value) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 78
   at GraphQL.ValueConverter.<>c__DisplayClass7_0`2.<Register>b__0(Object v) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 224
   at GraphQL.ValueConverter.TryConvertTo(Object value, Type targetType, Object& result, Type sourceType) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 183
   at GraphQL.ValueConverter.ConvertTo(Object value, Type targetType) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 157
   at GraphQL.Types.IntGraphType.ParseValue(Object value) in /_/src/GraphQL/Types/Scalars/IntGraphType.cs:line 24
   at GraphQL.Types.ScalarGraphType.Serialize(Object value) in /_/src/GraphQL/Types/Scalars/ScalarGraphType.cs:line 28
   at GraphQL.Execution.ExecutionStrategy.CompleteNode(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 302
   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 224
   at GraphQL.Execution.SerialExecutionStrategy.ExecuteNodeTreeAsync(ExecutionContext context, ObjectExecutionNode rootNode) in /_/src/GraphQL/Execution/SerialExecutionStrategy.cs:line 38
   at GraphQL.Execution.ExecutionStrategy.ExecuteAsync(ExecutionContext context) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 33
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 240
   at Epam.GraphQL.SchemaExecuter`1.ExecuteAsync(SchemaExecutionOptions`1 schemaExecutionOptions) in c:\EPM-PPA\epam-graphql\src\Epam.GraphQL\Schema\SchemaExecuter.cs:line 69
   at Epam.GraphQL.Extensions.MethodBaseExtensions.InvokeAndHoistBaseException[TResult](MethodBase methodBase, Object obj, Object[] parameters) in c:\EPM-PPA\epam-graphql\src\Epam.GraphQL\Extensions\MethodBaseExtensions.cs:line 42
   at Epam.GraphQL.Tests.Helpers.ExecuteHelpers.ExecuteQuery(Type queryType, Type mutationType, String request, IDataContext dataContext, Action`1 configure) in c:\EPM-PPA\epam-graphql\src\Tests\Epam.GraphQL.TestHelpers\Helpers\ExecuteHelpers.cs:line 28
   at Epam.GraphQL.Tests.Helpers.TestHelpers.TestQuery(Action`1 builder, String query, String expected, IDataContext dataContext, Action checks, Action beforeExecute, Action`1 optionsBuilder) in c:\EPM-PPA\epam-graphql\src\Tests\Epam.GraphQL.TestHelpers\Helpers\TestHelpers.cs:line 40
   at Epam.GraphQL.Tests.Resolve.DataTypesTests.BigLong() in c:\EPM-PPA\epam-graphql\src\Tests\Epam.GraphQL.Tests\Resolve\DataTypesTests.cs:line 19
```

### Steps to reproduce

Use unit test:
```
    [TestFixture]
    public class DataTypesTests : BaseTests
    {
        [Test]
        public void BigLong()
        {
            long value = 8350000000000066569;

            TestHelpers.TestQuery(
                builder: builder =>
                {
                    builder.Field("test").Resolve(_ => value);
                },
                query: @"query { test } ",
                expected: @"
                    {
                        ""test"": 8350000000000066569
                    }");
        }
    }
```

### Additional Context

v2.3.0

**Comment by pbanerji17** [comment]
Hi @IharYakimushEpam 

I cannot find the file DataTypesTests.cs in repo.
Do we need to fix this bug ?

**Comment by IharYakimushEpam** [comment]
Hi @pbanerji17 . DataTypesTests.cs is not in the repo. It is in "Steps to reproduce" section of description.
